### ISSUE TITLE
error installing on Mac Python 2.7

### ISSUE THREAD

**Issue by luzer** [pmeyers279/basketball_db#16]
```
imac:basketball_db-master$ python setup.py 
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    vcinfo(VERSION_PY)
  File "/xxx/basketball_db-master/utils/version.py", line 165, in __call__
    self.get_commit_info()
  File "/xxx/basketball_db-master/utils/version.py", line 78, in get_commit_info
    'log', '-1', '--pretty=format:%H,%ct,%an,%ae,%cn,%ce').split(',')
  File "/xxx/basketball_db-master/utils/version.py", line 68, in git
    ' '.join(cmdargs))
subprocess.CalledProcessError: Command '/usr/bin/git log -1 --pretty=format:%H,%ct,%an,%ae,%cn,%ce' returned non-zero exit status 128

```

**Comment by luzer** [comment]
fixed using git clone
